fix(yml): linting fixes

diff --git a/.github/workflows/semgrep.yml b/.github/workflows/semgrep.yml
--- a/.github/workflows/semgrep.yml
+++ b/.github/workflows/semgrep.yml
@@ -1,8 +1,8 @@
 ---
 name: "Semgrep checks"
 "on":
-    pull_request:
-    push:
+  pull_request:
+  push:
 
 jobs:
   semgrep:
@@ -16,15 +16,15 @@ jobs:
     if: (github.actor != 'dependabot[bot]')
 
     steps:
-        # Fetch project source with GitHub Actions Checkout.
-        - uses: actions/checkout@v4
-        - name: Run semgrep
-          run: |
-            ls -lah
-            ./semgrep.sh
-        - name: Publish Test Report
-          uses: mikepenz/action-junit-report@v4
-          if: success() || failure() # always run even if the previous step fails
-          with:
-            check_name: Semgrep Checks
-            report_paths: 'results.xml'
+      - uses: actions/checkout@v4
+      - name: Run semgrep
+        run: |
+          ls -lah
+          ./semgrep.sh
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure()
+        # always run even if the previous step fails
+        with:
+          check_name: Semgrep Checks
+          report_paths: 'results.xml'
